version: '3.8'

services:

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - atk-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - discovery-service
    ports:
      - "8080:8080"
    networks:
      - atk-net

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - discovery-service
    ports:
      - "8081:8081"
    networks:
      - atk-net

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - discovery-service
    ports:
      - "8082:8082"
    networks:
      - atk-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - atk-net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - atk-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" #AMQP protocol
      - "15672:15672" # Web management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - atk-net

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - discovery-service
      - rabbitmq
    ports:
      - "8083:8083"
    networks:
      - atk-net

  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - discovery-service
      - rabbitmq
    ports:
      - "8084:8084"
    networks:
      - atk-net

  shipping-service:
    build: ./shipping-service
    container_name: shipping-service
    depends_on:
      - discovery-service
      - rabbitmq
    ports:
      - "8085:8085"
    networks:
      - atk-net

networks:
  atk-net:
    driver: bridge
