server:
  port: 8085

spring:
  application:
    name: shipping-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/